### ISSUE TITLE
start

### ISSUE THREAD

**Issue by viunyrk** [tylermcginnis/rrssr#2]
Hello, could you please explain how did you manage to use this command  
"start": "webpack -w & nodemon server.js".
When I run it on windows webpack builds and starts watching files, and second command just don't start.
Thank you.

**Comment by mpolinowski** [comment]
Hi @41x ,

I just ran into the same issue - seems to be a macOS v. Windows Problem. You can change the npm scripts to something like:

```json
"scripts": {
    "start": "npm run wp | npm run nm",
    "test": "echo \"Error: no test specified\" && exit 1",
    "wp": "webpack --watch",
    "nm": "nodemon server.js"
  },
```

This works for me (Windows 10, Node 10, npm 6)


Cheers

**Comment by thamizhchelvan** [comment]
I tried with npm-run-all in Windows, it works:

  "scripts": {
    "start": "npm-run-all --parallel open:src open:watch",
    "open:src": "webpack -w",
    "open:watch": "nodemon server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  }

**Comment by mpolinowski** [comment]
@thamizhchelvan is there an advantage with npm-run-all over just piping both tasks together?

**Comment by thamizhchelvan** [comment]
@mpolinowski  npm-run-all is helpful to run multiple npm-scripts in parallel in Windows machines.

**Comment by meetaayush** [comment]
You can use [concurrently](https://github.com/kimmobrunfeldt/concurrently) to run multiple npm-scripts.

`"scripts: {
    "start": "concurrently \"webpack -w\" \"nodemon server.js\""
  }`

**Comment by viunyrk** [comment]
Thank you.

**Comment by midnightcodr** [comment]
Getting a bit lost here, where is `server.js` in the start script?

Edit: never mind, just found out - it's produced by the webpack command.
